CHATBOT
dsolomatinn/NIX_java_education_Solomatin_Danil pull request #2
Opened 2021-10-13 04:32 UTC by dsolomatinn

chatbot 2-nd  stage

chatbot stage#3

chatbot stage#4

chatbot stage#5

2021-10-14 19:13 UTC, MaximSomochkin requested changes

2021-10-14 19:13 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +        Scanner scanner1 = new Scanner(System.in);
Почему бы не использовать уже созданный ранее сканнер scanner, кажется в новых scanner1,2,3 нет необходимости

2021-10-14 19:13 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +        label:
Не используй метки(будут бить по рукам)

2021-10-14 19:13 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +        switch (answer){
Замени  switch на if-else

2021-10-16 08:28 UTC, asrubel approved these changes

2021-10-16 11:54 UTC, merged